In [3]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 4, 6, 9])
a

array([1, 4, 6, 9])

In [11]:
a[1] = 10
a

array([ 1, 10,  6,  9])

In [13]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
n[0,1]

np.int64(2)

In [17]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[0]

array([ 1, 20,  3])

In [20]:
n[0] = [10,20,30]
n

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[:,1] = [100, 200, 300]
n

array([[ 10, 100,  30],
       [  4, 200,   6],
       [  7, 300,   9]])

In [30]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [32]:
# standard normal distribution
np.random.randn(5,2)

array([[-1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ],
       [ 0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221]])

In [33]:
np.random.randint(low=0, high=100, size=(5,2))

array([[23, 94],
       [11, 28],
       [74, 88],
       [ 9, 15],
       [18, 80]])

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
a * 2

array([0, 2, 4, 6, 8])

In [39]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [40]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [44]:
a

array([0, 1, 2, 3, 4])

In [42]:
a >= 2

array([False, False,  True,  True,  True])

In [45]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [46]:
a > b

array([False, False,  True,  True,  True])

In [47]:
a[a > b]

array([2, 3, 4])

In [48]:
a.min()

np.int64(0)

In [49]:
a.sum()

np.int64(10)

In [50]:
a.mean()

np.float64(2.0)

In [51]:
a.std()

np.float64(1.4142135623730951)

In [52]:
n

array([[ 10, 100,  30],
       [  4, 200,   6],
       [  7, 300,   9]])

In [53]:
n.min()

np.int64(4)

# Linear Algebra

## Multiplication

In [6]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
u * v

array([ 2,  0,  0, 12])

In [8]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]

    return result
vector_vector_multiplication(u,v)

np.float64(14.0)

In [9]:
u.dot(v)

np.int64(14)

In [10]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [11]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [12]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [16]:
result = matrix_vector_multiplication(U, v)
result.shape

(3,)

In [17]:
U.dot(v)

array([14,  5,  5])

In [19]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [22]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:,i]
        result[:,i] = matrix_vector_multiplication(U, vi)
    return result
    

In [23]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [24]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix 

In [32]:
I = np.eye(4)

In [33]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [34]:
I.dot(V)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
vs = V[[0,1,2]] # fancy indexing or advanced indexing in NumPy
vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [37]:
# Select column 1 twice
testv = V[:, [1, 1]]
testv

array([[1. , 1. ],
       [0.5, 0.5],
       [2. , 2. ],
       [1. , 1. ]])

In [39]:
vs_inv = np.linalg.inv(vs)
vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [40]:
vs_inv.dot(vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])