In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 4, 6, 9])
a

array([1, 4, 6, 9])

In [11]:
a[1] = 10
a

array([ 1, 10,  6,  9])

In [13]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
n[0,1]

np.int64(2)

In [17]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[0]

array([ 1, 20,  3])

In [20]:
n[0] = [10,20,30]
n

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[:,1] = [100, 200, 300]
n

array([[ 10, 100,  30],
       [  4, 200,   6],
       [  7, 300,   9]])

In [30]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [32]:
# standard normal distribution
np.random.randn(5,2)

array([[-1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ],
       [ 0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221]])

In [33]:
np.random.randint(low=0, high=100, size=(5,2))

array([[23, 94],
       [11, 28],
       [74, 88],
       [ 9, 15],
       [18, 80]])

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
a * 2

array([0, 2, 4, 6, 8])

In [39]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [40]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [44]:
a

array([0, 1, 2, 3, 4])

In [42]:
a >= 2

array([False, False,  True,  True,  True])

In [45]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [46]:
a > b

array([False, False,  True,  True,  True])

In [47]:
a[a > b]

array([2, 3, 4])

In [48]:
a.min()

np.int64(0)

In [49]:
a.sum()

np.int64(10)

In [50]:
a.mean()

np.float64(2.0)

In [51]:
a.std()

np.float64(1.4142135623730951)

In [52]:
n

array([[ 10, 100,  30],
       [  4, 200,   6],
       [  7, 300,   9]])

In [53]:
n.min()

np.int64(4)